### ISSUE TITLE
默认网关的问题

### ISSUE THREAD

**Issue by Leoyzen** [ashi009/bestroutetb#16]
尝试过很多次，好像这个项目的默认路由都是走VPN的。
不知道楼主是否可以考虑加入个功能，就是根据默认网关是VPN还是NET，这样会衍生很多很多应用。
比如多拨N个VPN，为每个VPN生成不同的路由表，例如香港的走香港VPN,美国的走美国VPN；
比如可以设置某个国家例如美国的走VPN，其他所有国家的都走NET。
这样话可定制化很高；
还可以设置个参数外挂个文件当做IP白名单，不知道LZ什么意见呢?
我也是爱折腾的人，想通过LZ的这些方法整合个可靠地项目。

**Comment by ashi009** [comment]
You may want to try version in the other opening issue, it supports
multi-vpn optimization. And for the case that you only need two gateways,
master version has the features you requested. Please check out the wiki.

**Comment by luginbash** [comment]
Though you have multiple VPNs, you can generate routes that are defaulted to your vanilla one.
This SHOULD work as long as the routes are not intersecting.

**Comment by ashi009** [comment]
You may specify the gateway for 0.0.0.0/0.

**Comment by Leoyzen** [comment]
我尝试过了。比如你给的openwrt 实例中的脚本，我直接使用生成的ip-up.sh，测试中完全都是走的国外线路
我也尝试使用例如
./generate.js --net=cn,0.0.0.0/0 --vpn=us --nodefaultgw=1 --profile=iproute_up
结果生成的依旧是大部分流量走的VPN，国内走的NET，即便不生成默认网关和要求0/0走NET，脚本依旧会使用0/2为VPN路由。例如我生成的脚本：
ip -b - <<FILE
r a 0.0.0.0/2 via $5
r a 0.0.0.0/7 via $netgw
r a 8.0.0.0/9 via $netgw
r a 14.0.0.0/8 via $netgw
r a 27.0.0.0/8 via $netgw
r a 36.0.0.0/8 via $netgw
r a 39.0.0.0/8 via $netgw
r a 42.0.0.0/7 via $netgw
r a 49.0.0.0/8 via $netgw
r a 54.222.0.0/15 via $netgw
r a 58.0.0.0/7 via $netgw
r a 60.0.0.0/7 via $netgw
r a 60.254.0.0/16 via $5
r a 64.0.0.0/3 via $5
r a 91.232.0.0/13 via $netgw
r a 96.0.0.0/6 via $5
r a 100.0.0.0/8 via $5
r a 103.246.248.0/21 via $5
r a 107.0.0.0/8 via $5
r a 108.0.0.0/7 via $5
r a 113.29.0.0/17 via $5
r a 128.0.0.0/1 via $5
r a 204.79.168.0/22 via $netgw
r a 204.79.189.0/24 via $netgw
r a 206.219.0.0/18 via $netgw
r a 206.220.132.0/22 via $netgw
r a 206.225.128.0/22 via $netgw
FILE
关于其他issue里的项目，我看看。感谢楼主提供这么好的项目。
我主要不是想用iproute，我在尝试建立不同的地区不同的Ip  rule

**Comment by ashi009** [comment]
Because the US took huge ip chunks, it's very unlikely to get it optimized
if the vpn gateway is not defaut one.

我尝试过了。比如你给的openwrt 实例中的脚本，我直接使用生成的ip-up.sh，测试中完全都是走的国外线路
我也尝试使用例如
./generate.js --net=cn,0.0.0.0/0 --vpn=us --nodefaultgw=1
--profile=iproute_up
结果生成的依旧是大部分流量走的VPN，国内走的NET，即便不生成默认网关和要求0/0走NET，脚本依旧会使用0/2为VPN路由。例如我生成的脚本：
ip -b - <<FILE
r a 0.0.0.0/2 via $5
r a 0.0.0.0/7 via $netgw
r a 8.0.0.0/9 via $netgw
r a 14.0.0.0/8 via $netgw
r a 27.0.0.0/8 via $netgw
r a 36.0.0.0/8 via $netgw
r a 39.0.0.0/8 via $netgw
r a 42.0.0.0/7 via $netgw
r a 49.0.0.0/8 via $netgw
r a 54.222.0.0/15 via $netgw
r a 58.0.0.0/7 via $netgw
r a 60.0.0.0/7 via $netgw
r a 60.254.0.0/16 via $5
r a 64.0.0.0/3 via $5
r a 91.232.0.0/13 via $netgw
r a 96.0.0.0/6 via $5
r a 100.0.0.0/8 via $5
r a 103.246.248.0/21 via $5
r a 107.0.0.0/8 via $5
r a 108.0.0.0/7 via $5
r a 113.29.0.0/17 via $5
r a 128.0.0.0/1 via $5
r a 204.79.168.0/22 via $netgw
r a 204.79.189.0/24 via $netgw
r a 206.219.0.0/18 via $netgw
r a 206.220.132.0/22 via $netgw
r a 206.225.128.0/22 via $netgw
FILE
关于其他issue里的项目，我看看。感谢楼主提供这么好的项目。
我主要不是想用iproute，我在尝试建立不同的地区不同的Ip rule

—
Reply to this email directly or view it on
GitHubhttps://github.com/ashi009/bestroutetb/issues/16#issuecomment-30301693
.
